server:
  port: 8061
spring:
  application:
    name: sso-system
  cloud:
    nacos:
      discovery:
        server-addr: localhost
      config:
        server-addr: localhost
        file-extension: yml
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSsl=false&characterEncoding=utf8
    username: root
    password: root
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'